// export const data = {
//   admin: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//       id: 1,
//     },

//     {
//       name: 'report',
//       icon: 'report',
//       url: 'report',
//       id: 'report',
//       children: [
//         {
//           name: 'report.overview',
//           icon: 'overview',
//           url: 'report/overview',
//           id: 'report-overview',
//         },
//         {
//           name: 'report.products',
//           icon: 'products',
//           url: 'report/products',
//           id: 'report-products',
//         },
//         {
//           name: 'report.revenue',
//           icon: 'revenue',
//           url: 'report/revenue',
//           id: 'report-revenue',
//         },
//         {
//           name: 'report.orders',
//           icon: 'orders',
//           url: 'report/orders',
//           id: 'report-orders',
//         },
//         {
//           name: 'report.categories',
//           icon: 'categories',
//           url: 'report/categories',
//           id: 'report-categories',
//         },
//       ],
//     },
//     {
//       name: 'catalog',
//       icon: 'gold',
//       url: 'catalog',
//       id: 8,
//       children: [
//         {
//           icon: 'dropbox',
//           url: 'catalog/products',
//           name: 'products',
//           id: 6,
//         },
//         {
//           name: 'categories',
//           icon: 'appStore',
//           url: 'catalog/categories',
//           id: 5,
//         },
//         {
//           name: 'brands',
//           icon: 'appStoreAdd',
//           url: 'catalog/brands',
//           id: 3,
//         },
//         {
//           name: 'units',
//           icon: 'disconnect',
//           url: 'catalog/units',
//           id: 26,
//         },
//         {
//           name: 'recipe.categories',
//           icon: 'orderedList',
//           url: 'catalog/recipe-categories',
//           id: 'recipe-categories',
//         },
//         {
//           name: 'groups',
//           icon: 'GrCatalog',
//           url: 'catalog/groups',
//           id: 'catalog-groups',
//         },
//       ],
//     },
//     {
//       name: 'orders',
//       icon: 'fiShoppingCart',
//       url: 'orders',
//       id: 14,
//     },
//     {
//       name: 'refund',
//       icon: 'refund',
//       url: 'refund',
//       id: 'refund',
//     },
//     {
//       name: 'transactions',
//       icon: 'transaction',
//       url: 'transactions',
//       id: 'transactions',
//     },
//     {
//       name: 'pos.system',
//       icon: 'laptop',
//       url: 'pos-system',
//       id: 4,
//     },
//     {
//       name: 'banners',
//       icon: 'bsImage',
//       url: 'banners',
//       id: 10,
//     },
//     {
//       name: 'reviews',
//       icon: 'star',
//       url: 'reviews',
//       id: 'reviews',
//       children: [
//         {
//           name: 'product.reviews',
//           icon: 'skin',
//           url: 'reviews/product',
//           id: 'product-review',
//         },
//         {
//           name: 'order.reviews',
//           icon: 'book',
//           url: 'reviews/order',
//           id: 'order-review',
//         },
//       ],
//     },
//     {
//       name: 'tickets',
//       icon: 'project',
//       url: 'tickets',
//       id: 24,
//     },
//     {
//       name: 'wallets',
//       icon: 'wallet',
//       url: 'wallets',
//       id: 'wallets',
//     },
//     // {
//     //   name: 'payout.requests',
//     //   icon: 'dollar',
//     //   url: 'payout-requests',
//     //   id: 'payout-requests',
//     // },
//     {
//       name: 'notifications',
//       icon: 'notificationsActive',
//       url: 'notifications',
//       id: 11,
//     },
//     {
//       name: 'subscriptions',
//       icon: 'imSubscript',
//       url: 'subscriptions',
//       id: 13,
//     },
//     {
//       name: 'cashback',
//       icon: 'copyright',
//       url: 'cashback',
//       id: 'cashback',
//     },
//     {
//       name: 'delivery',
//       icon: 'deliveryDining',
//       id: 'delivery',
//       url: 'delivery',
//       children: [
//         {
//           icon: 'deliveryDining',
//           name: 'delivery',
//           url: 'delivery/list',
//           id: 15,
//         },
//         {
//           icon: 'deliveryDining',
//           name: 'deliveryman',
//           url: 'delivery/deliveryman',
//           id: 16,
//         },
//       ],
//     },
//     {
//       name: 'gallery',
//       url: 'gallery',
//       icon: 'fiImage',
//       id: 17,
//     },
//     {
//       name: 'users',
//       id: 'user',
//       icon: 'user',
//       url: 'users',
//       children: [
//         {
//           icon: 'user',
//           url: 'users/user',
//           name: 'clients',
//           id: 18,
//         },
//         {
//           icon: 'userGroupAdd',
//           url: 'users/admin',
//           name: 'users',
//           id: 19,
//         },
//         {
//           icon: 'userSwitch',
//           url: 'users/role',
//           name: 'roles',
//           id: 20,
//         },
//       ],
//     },
//     {
//       name: 'blogs',
//       url: 'blogs',
//       icon: 'form',
//       id: 'blogs',
//     },

//     {
//       name: 'email.subscriber',
//       icon: 'mail',
//       url: 'email/subscriber',
//       id: 'email.subscriber',
//       children: [
//         {
//           icon: 'MdNotificationAdd',
//           url: 'subscriber',
//           name: 'subscriber',
//           id: 'subscriber',
//         },
//         {
//           icon: 'MdNotificationAdd',
//           url: 'message/subscriber',
//           name: 'message.subscriber',
//           id: 'message.subscriber',
//         },
//       ],
//     },
//     {
//       name: 'settings',
//       icon: 'settings',
//       url: 'settings',
//       id: 9,
//       children: [
//         {
//           icon: 'settings',
//           url: 'settings/general',
//           name: 'settings.general',
//           id: 21,
//         },
//         {
//           icon: 'global',
//           url: 'settings/languages',
//           name: 'languages',
//           id: 22,
//         },
//         {
//           icon: 'moneyCollect',
//           url: 'currencies',
//           name: 'currencies',
//           id: 12,
//         },
//         {
//           icon: 'translation',
//           url: 'settings/translations',
//           name: 'translations',
//           id: 23,
//         },
//         {
//           icon: 'database',
//           url: 'settings/backup',
//           name: 'backup',
//           id: 24,
//         },
//         {
//           icon: 'tool',
//           url: 'settings/system-information',
//           name: 'system.information',
//           id: 25,
//         },
//         // {
//         //   icon: 'wallet',
//         //   url: 'settings/payments',
//         //   name: 'payments',
//         //   id: 'payments',
//         // },
//         {
//           icon: 'message',
//           url: 'settings/sms-gateways',
//           name: 'sms-gateways',
//           id: 'sms-gateways',
//         },
//         {
//           icon: 'emailSettings',
//           url: 'settings/emailProviders',
//           name: 'email.provider',
//           id: 'email.provider',
//         },
//         {
//           icon: 'questionCircle',
//           url: 'settings/faqs',
//           name: 'FAQ',
//           id: 'faq',
//         },
//         {
//           icon: 'paperClip',
//           url: 'settings/terms',
//           name: 'terms',
//           id: 'terms',
//         },
//         {
//           icon: 'lock',
//           url: 'settings/policy',
//           name: 'policy',
//           id: 'policy',
//         },
//         {
//           icon: 'cloudUpload',
//           url: 'settings/update',
//           name: 'update',
//           id: 'update',
//         },
//         {
//           icon: 'fire',
//           url: 'settings/firebase',
//           name: 'firebase.config',
//           id: 'firebase-config',
//         },
//         {
//           icon: 'instagram',
//           url: 'settings/social',
//           name: 'social.settings',
//           id: 'social-settings',
//         },
//       ],
//     },

//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
//   manager: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//       id: 1,
//     },
//     {
//       name: 'shops',
//       icon: 'shop',
//       url: 'shops',
//       id: 2,
//     },
//     {
//       name: 'catalog',
//       icon: 'gold',
//       url: 'catalog',
//       id: 8,
//       children: [
//         {
//           icon: 'dropbox',
//           url: 'catalog/products',
//           name: 'products',
//           id: 6,
//         },
//         {
//           name: 'categories',
//           icon: 'appStore',
//           url: 'catalog/categories',
//           id: 5,
//         },
//         {
//           name: 'brands',
//           icon: 'appStoreAdd',
//           url: 'catalog/brands',
//           id: 3,
//         },
//         {
//           name: 'units',
//           icon: 'disconnect',
//           url: 'catalog/units',
//           id: 26,
//         },
//         {
//           name: 'recipe.categories',
//           icon: 'orderedList',
//           url: 'catalog/recipe-categories',
//           id: 'recipe-categories',
//         },
//         {
//           name: 'groups',
//           icon: 'GrCatalog',
//           url: 'catalog/groups',
//           id: 'catalog-groups',
//         },
//       ],
//     },
//     {
//       name: 'orders',
//       icon: 'fiShoppingCart',
//       url: 'orders',
//       id: 14,
//     },
//     {
//       name: 'transactions',
//       icon: 'transaction',
//       url: 'transactions',
//       id: 'transactions',
//     },
//     {
//       name: 'pos.system',
//       icon: 'laptop',
//       url: 'pos-system',
//       id: 4,
//     },
//     {
//       name: 'banners',
//       icon: 'bsImage',
//       url: 'banners',
//       id: 10,
//     },
//     {
//       name: 'reviews',
//       icon: 'star',
//       url: 'reviews',
//       id: 'reviews',
//       children: [
//         {
//           name: 'product.reviews',
//           icon: 'skin',
//           url: 'reviews/product',
//           id: 'product-review',
//         },
//         {
//           name: 'order.reviews',
//           icon: 'book',
//           url: 'reviews/order',
//           id: 'order-review',
//         },
//       ],
//     },
//     {
//       name: 'tickets',
//       icon: 'project',
//       url: 'tickets',
//       id: 24,
//     },
//     {
//       name: 'wallets',
//       icon: 'wallet',
//       url: 'wallets',
//       id: 'wallets',
//     },
//     // {
//     //   name: 'payout.requests',
//     //   icon: 'dollar',
//     //   url: 'payout-requests',
//     //   id: 'payout-requests',
//     // },
//     {
//       name: 'notifications',
//       icon: 'notificationsActive',
//       url: 'notifications',
//       id: 11,
//     },
//     {
//       name: 'subscriptions',
//       icon: 'imSubscript',
//       url: 'subscriptions',
//       id: 13,
//     },
//     {
//       name: 'delivery',
//       icon: 'deliveryDining',
//       id: 'delivery',
//       url: 'delivery',
//       children: [
//         {
//           icon: 'deliveryDining',
//           name: 'delivery',
//           url: 'delivery/list',
//           id: 15,
//         },
//         {
//           icon: 'deliveryDining',
//           name: 'deliveryman',
//           url: 'delivery/deliveryman',
//           id: 16,
//         },
//       ],
//     },
//     {
//       name: 'users',
//       id: 'user',
//       icon: 'user',
//       url: 'users',
//       children: [
//         {
//           icon: 'user',
//           url: 'users/user',
//           name: 'clients',
//           id: 18,
//         },
//         {
//           icon: 'userGroupAdd',
//           url: 'users/admin',
//           name: 'users',
//           id: 19,
//         },
//         {
//           icon: 'userSwitch',
//           url: 'users/role',
//           name: 'roles',
//           id: 20,
//         },
//       ],
//     },
//     {
//       name: 'blogs',
//       url: 'blogs',
//       icon: 'form',
//       id: 'blogs',
//     },
//     {
//       name: 'settings',
//       icon: 'settings',
//       url: 'settings',
//       id: 9,
//       children: [
//         {
//           icon: 'settings',
//           url: 'settings/general',
//           name: 'settings.general',
//           id: 21,
//         },
//         {
//           icon: 'global',
//           url: 'settings/languages',
//           name: 'languages',
//           id: 22,
//         },
//         {
//           icon: 'moneyCollect',
//           url: 'currencies',
//           name: 'currencies',
//           id: 12,
//         },
//         {
//           icon: 'translation',
//           url: 'settings/translations',
//           name: 'translations',
//           id: 23,
//         },
//         {
//           icon: 'database',
//           url: 'settings/backup',
//           name: 'backup',
//           id: 24,
//         },
//         {
//           icon: 'tool',
//           url: 'settings/system-information',
//           name: 'system.information',
//           id: 25,
//         },
//         {
//           icon: 'message',
//           url: 'settings/sms-gateways',
//           name: 'sms-gateways',
//           id: 'sms-gateways',
//         },
//         {
//           icon: 'questionCircle',
//           url: 'settings/faqs',
//           name: 'FAQ',
//           id: 'faq',
//         },
//         {
//           icon: 'paperClip',
//           url: 'settings/terms',
//           name: 'terms',
//           id: 'terms',
//         },
//         {
//           icon: 'lock',
//           url: 'settings/policy',
//           name: 'policy',
//           id: 'policy',
//         },
//         {
//           icon: 'cloudUpload',
//           url: 'settings/update',
//           name: 'update',
//           id: 'update',
//         },
//         {
//           icon: 'fire',
//           url: 'settings/firebase',
//           name: 'firebase.config',
//           id: 'firebase-config',
//         },
//         {
//           icon: 'instagram',
//           url: 'settings/social',
//           name: 'social.settings',
//           id: 'social-settings',
//         },
//       ],
//     },
//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
//   seller: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//     },
//     {
//       name: 'pos.system',
//       icon: 'laptop',
//       url: 'seller/pos-system',
//       id: 'pos-system',
//     },
//     {
//       name: 'subscriptions',
//       icon: 'trophy',
//       url: 'seller/subscriptions',
//       id: 'subscription',
//     },
//     {
//       icon: 'dropbox',
//       url: 'seller/products',
//       name: 'Products',
//       id: 6,
//     },
//     {
//       name: 'categories',
//       icon: 'appStore',
//       url: 'seller/categories',
//       id: 5,
//     },
//     {
//       name: 'brands',
//       icon: 'appStoreAdd',
//       url: 'seller/brands',
//       id: 3,
//     },
//     {
//       name: 'bonus',
//       icon: 'GiftOutlined',
//       url: 'seller/bonus',
//       id: 44,
//       children: [
//         {
//           icon: 'GiftOutlined',
//           name: 'product.bonus',
//           url: 'seller/bonus/product',
//           id: 'bonus/product',
//         },
//         {
//           icon: 'GiftOutlined',
//           name: 'shop.bonus',
//           url: 'seller/bonus/shop',
//           id: 'bonus/shop',
//         },
//       ],
//     },
//     {
//       name: 'branch',
//       icon: 'branchesOutlined',
//       url: 'seller/branch',
//       id: 'branch',
//     },
//     {
//       name: 'payments',
//       icon: 'wallet',
//       url: 'seller/payments',
//       id: 'payments',
//     },
//     {
//       name: 'banners',
//       icon: 'bsImage',
//       url: 'seller/banner',
//       id: 'SellerBanner',
//     },
//     {
//       name: 'my.shop',
//       icon: 'shop',
//       id: 'my-shop',
//       url: 'my-shop',
//     },
//     {
//       name: 'orders',
//       icon: 'fiShoppingCart',
//       url: 'seller/orders',
//       id: 'orders',
//     },
//     {
//       name: 'recipes',
//       icon: 'orderedList',
//       url: 'seller/recipes',
//       id: 'recipes',
//     },
//     {
//       name: 'coupons',
//       icon: 'calendar',
//       url: 'coupons',
//     },
//     {
//       name: 'discounts',
//       icon: 'euroCircle',
//       url: 'seller/discounts',
//     },
//     {
//       name: 'invites',
//       icon: 'orderedList',
//       url: 'seller/invites',
//     },
//     // {
//     //   name: 'payouts',
//     //   icon: 'dollar',
//     //   url: 'seller/payouts',
//     // },
//     {
//       name: 'delivery',
//       icon: 'deliveryDining',
//       id: 'delivery',
//       url: 'delivery',
//       children: [
//         {
//           icon: 'deliveryDining',
//           name: 'delivery',
//           url: 'seller/delivery/list',
//           id: 15,
//         },
//         {
//           icon: 'deliveryDining',
//           name: 'deliveryman',
//           url: 'seller/delivery/deliveryman',
//           id: 16,
//         },
//       ],
//     },
//     {
//       name: 'users',
//       id: 'users',
//       icon: 'user',
//       url: 'seller/shop-users',
//     },
//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
//   moderator: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//     },
//     {
//       name: 'pos.system',
//       icon: 'laptop',
//       url: 'seller/pos-system',
//       id: 'pos-system',
//     },
//     {
//       icon: 'dropbox',
//       url: 'seller/products',
//       name: 'Products',
//       id: 6,
//     },
//     {
//       name: 'categories',
//       icon: 'appStore',
//       url: 'seller/categories',
//       id: 5,
//     },
//     {
//       name: 'brands',
//       icon: 'appStoreAdd',
//       url: 'seller/brands',
//       id: 3,
//     },
//     {
//       name: 'my.shop',
//       icon: 'shop',
//       id: 'my-shop',
//       url: 'my-shop',
//     },
//     {
//       name: 'orders',
//       icon: 'fiShoppingCart',
//       url: 'seller/orders',
//       id: 'orders',
//     },
//     {
//       name: 'discounts',
//       icon: 'euroCircle',
//       url: 'seller/discounts',
//     },
//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
//   deliveryman: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//       id: 'dashboard',
//     },
//     {
//       name: 'orders',
//       icon: 'fiShoppingCart',
//       url: 'deliveryman/orders',
//       id: 'orders',
//     },
//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
//   user: [
//     {
//       name: 'dashboard',
//       icon: 'dashboard',
//       url: 'dashboard',
//       id: 1,
//     },
//     {
//       name: 'Shops',
//       icon: 'shop',
//       id: 'shops',
//     },
//     {
//       name: 'Brand',
//       icon: 'appStoreAdd',
//       id: 'brand',
//     },
//     {
//       name: 'POS System',
//       icon: 'laptop',
//       url: 'pos-system',
//       id: 'pos-system',
//     },
//     {
//       name: 'user',
//       icon: 'moneyCollect',
//       id: 'user',
//     },
//     {
//       name: 'logout',
//       icon: 'logout',
//       id: 'logout',
//       url: '',
//     },
//   ],
// };

const adminRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 1,
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'pos-system',
    id: 4,
  },
  {
    name: 'order.management',
    id: 'order.management',
    submenu: [
      {
        name: 'orders',
        icon: 'fiShoppingCart',
        url: 'orders',
        id: 14,
      },
      {
        name: 'refund',
        icon: 'refund',
        url: 'refund',
        id: 'refund',
      },
    ],
  },
  {
    name: 'deliveryman.management',
    id: 'deliveryman.management',
    submenu: [
      {
        icon: 'deliveryDining',
        name: 'delivery',
        url: 'delivery/list',
        id: 15,
      },
      {
        icon: 'deliveryDining',
        name: 'deliveryman',
        url: 'delivery/deliveryman',
        id: 16,
      },
    ],
  },
  {
    name: 'shop.management',
    id: 'shop.managements',
    submenu: [
      {
        name: 'shops',
        icon: 'shop',
        url: 'shops',
        id: 'shops',
        children: [],
      },
      {
        name: 'categories',
        icon: 'appStore',
        url: 'catalog/categories',
        id: 5,
      },
      {
        name: 'recipe.categories',
        icon: 'orderedList',
        url: 'catalog/recipe-categories',
        id: 'recipe-categories',
      },
      {
        name: 'groups',
        icon: 'GrCatalog',
        url: 'catalog/groups',
        id: 'catalog-groups',
      },
    ],
  },
  {
    name: 'content.management',
    id: 'content.management',
    submenu: [
      {
        name: 'brands',
        icon: 'appStoreAdd',
        url: 'catalog/brands',
        id: 'brands',
        children: [],
      },
      {
        name: 'units',
        icon: 'disconnect',
        url: 'catalog/units',
        id: 'units',
        children: [],
      },
      {
        name: 'banners',
        icon: 'bsImage',
        url: 'banners',
        id: 10,
        children: [],
      },
      {
        name: 'blogs',
        url: 'blogs',
        icon: 'form',
        id: 'blogs',
        children: [],
      },
      {
        name: 'gallery',
        url: 'gallery',
        icon: 'fiImage',
        id: 17,
        children: [],
      },
      {
        name: 'notifications',
        icon: 'notificationsActive',
        url: 'notifications',
        id: 11,
        children: [],
      },
    ],
  },
  {
    name: 'customer.management',
    id: 'customer.management',
    submenu: [
      {
        name: 'wallets',
        icon: 'wallet',
        url: 'wallets',
        id: 'wallets',
        children: [],
      },
      {
        name: 'users',
        id: 'user',
        icon: 'user',
        url: 'users',
        children: [
          {
            icon: 'user',
            url: 'users/user',
            name: 'clients',
            id: 18,
          },
          {
            icon: 'userGroupAdd',
            url: 'users/admin',
            name: 'users',
            id: 19,
          },
          {
            icon: 'userSwitch',
            url: 'users/role',
            name: 'roles',
            id: 20,
          },
        ],
      },
      {
        name: 'email.subscriber',
        icon: 'mail',
        url: 'email/subscriber',
        id: 'email.subscriber',
        children: [
          {
            icon: 'MdNotificationAdd',
            url: 'subscriber',
            name: 'subscriber',
            id: 'subscriber',
          },
          {
            icon: 'MdNotificationAdd',
            url: 'message/subscriber',
            name: 'message.subscriber',
            id: 'message.subscriber',
          },
        ],
      },
    ],
  },
  {
    name: 'transaction.management',
    id: 'transaction.management',
    submenu: [
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'transactions',
        id: 'transactions',
        children: [],
      },
      {
        name: 'payout.requests',
        icon: 'dollar',
        url: 'payout-requests',
        id: 'payout-requests',
        children: [],
      },
      {
        name: 'payouts',
        icon: 'dollar',
        url: 'payouts',
        id: 'payouts',
        children: [],
      },
      {
        name: 'subscriptions',
        icon: 'imSubscript',
        url: 'subscriptions',
        id: 13,
        children: [],
      },
    ],
  },
  {
    name: 'marketing',
    id: 'restaurant.management',
    submenu: [
      {
        name: 'cashback',
        icon: 'copyright',
        url: 'cashback',
        id: 'cashback',
        children: [],
      },
      // {
      //   icon: 'referral',
      //   url: 'settings/referal',
      //   name: 'referral',
      //   id: 'referral',
      //   children: [],
      // },
    ],
  },
  {
    name: 'ANALYTICS.ADN.REPORTS',
    id: 'analytics',
    submenu: [
      {
        name: 'products',
        icon: 'products',
        url: 'report/products',
        id: 'report-products',
        children: [],
      },
      {
        name: 'order',
        icon: 'orders',
        url: 'report/orders',
        id: 'report-orders',
        children: [],
      },
      {
        name: 'category',
        icon: 'categories',
        url: 'report/categories',
        id: 'report-categories',
        children: [],
      },
      {
        name: 'overview',
        icon: 'overview',
        url: 'report/overview',
        id: 'report-overview',
        children: [],
      },
      {
        name: 'revenue',
        icon: 'revenue',
        url: 'report/revenue',
        id: 'report-revenue',
        children: [],
      },
    ],
  },

  {
    name: 'business.settings',
    id: 'business.settings',
    submenu: [
      {
        icon: 'settings',
        url: 'settings/general',
        name: 'settings.general',
        id: 'settings.general',
        children: [],
      },
      {
        icon: 'moneyCollect',
        url: 'currencies',
        name: 'currencies',
        id: 'currencies',
        children: [],
      },
      {
        icon: 'wallet',
        url: 'settings/payments',
        name: 'payments',
        id: 'payments',
        children: [],
      },
      {
        icon: 'message',
        url: 'settings/sms-gateways',
        name: 'sms-gateways',
        id: 'sms-gateways',
        children: [],
      },
      {
        icon: 'emailSettings',
        url: 'settings/emailProviders',
        name: 'email.provider',
        id: 'email.provider',
        children: [],
      },
      {
        icon: 'notificationsActive',
        url: 'settings/firebase',
        name: 'notification.settings',
        id: 'notification.settings',
        children: [],
      },
      {
        icon: 'instagram',
        url: 'settings/social',
        name: 'social.settings',
        id: 'social-settings',
        children: [],
      },
      {
        icon: 'settings',
        url: 'settings',
        name: 'page.setup',
        id: 'page.setup',
        children: [
          {
            icon: 'questionCircle',
            url: 'settings/faqs',
            name: 'FAQ',
            id: 'faq',
          },
          {
            icon: 'paperClip',
            url: 'settings/terms',
            name: 'terms',
            id: 'terms',
          },
          {
            icon: 'lock',
            url: 'settings/policy',
            name: 'policy',
            id: 'policy',
          },
        ],
      },
    ],
  },
  {
    name: 'system.settings',
    id: 'system.settings',
    submenu: [
      {
        icon: 'global',
        url: 'settings/languages',
        name: 'languages',
        id: 'languages',
        children: [],
      },
      {
        icon: 'translation',
        url: 'settings/translations',
        name: 'translations',
        id: 'translations',
        children: [],
      },
      {
        icon: 'database',
        url: 'settings/backup',
        name: 'backup',
        id: 'backup',
        children: [],
      },
      {
        icon: 'tool',
        url: 'settings/system-information',
        name: 'system.information',
        id: 'system.information',
        children: [],
      },
      {
        icon: 'cloudUpload',
        url: 'settings/update',
        name: 'update',
        id: 'update',
        children: [],
      },
    ],
  },
  {
    name: 'cashback.settings',
    id: 'cashback.settings',
    submenu: [
      {
        icon: 'birthday',
        url: 'settings/birthday',
        name: 'birthday',
        id: 'birthday',
        children: [],
      },
      {
        icon: 'day',
        url: 'settings/day',
        name: 'day',
        id: 'day',
        children: [],
      },
    ],
  },
  // {
  //   name: 'tickets',
  //   icon: 'project',
  //   url: 'tickets',
  //   id: 24,
  // },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

const managerRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 1,
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'pos-system',
    id: 4,
  },
  {
    name: 'order.management',
    id: 'order.management',
    submenu: [
      {
        name: 'orders',
        icon: 'fiShoppingCart',
        url: 'orders',
        id: 14,
        children: [],
      },
      {
        name: 'order.reviews',
        icon: 'book',
        url: 'reviews/order',
        id: 'order-review',
        children: [],
      },
    ],
  },
  {
    name: 'shop.management',
    id: 'shop.management',
    submenu: [
      {
        name: 'shops',
        icon: 'shop',
        url: 'shops',
        id: 'shops',
        children: [],
      },
    ],
  },
  {
    name: 'report.management',
    id: 'report.management',
    submenu: [
      {
        name: 'product.report',
        icon: 'products',
        url: 'report/products',
        id: 'report-products',
        children: [],
      },
      {
        name: 'order.report',
        icon: 'orders',
        url: 'report/orders',
        id: 'report-orders',
        children: [],
      },
      {
        name: 'category.report',
        icon: 'categories',
        url: 'report/categories',
        id: 'report-categories',
        children: [],
      },
      {
        name: 'overview',
        icon: 'overview',
        url: 'report/overview',
        id: 'report-overview',
        children: [],
      },
      {
        name: 'revenue',
        icon: 'revenue',
        url: 'report/revenue',
        id: 'report-revenue',
        children: [],
      },
    ],
  },
  {
    name: 'product.management',
    id: 'product.management',
    submenu: [
      {
        name: 'products',
        icon: 'dropbox',
        url: 'catalog/products',
        id: 'product',
        children: [],
      },
      // {
      //   name: 'product.reviews',
      //   icon: 'skin',
      //   url: 'reviews/product',
      //   id: 'product-review',
      //   children: [],
      // },
      {
        name: 'catalog',
        icon: 'gold',
        url: 'catalog',
        id: 8,
        children: [
          {
            name: 'categories',
            icon: 'appStore',
            url: 'catalog/categories',
            id: 5,
          },
          {
            name: 'recipe.categories',
            icon: 'orderedList',
            url: 'catalog/recipe-categories',
            id: 'recipe-categories',
          },
          {
            name: 'brands',
            icon: 'appStoreAdd',
            url: 'catalog/brands',
            id: 'brands',
          },
          {
            name: 'units',
            icon: 'disconnect',
            url: 'catalog/units',
            id: 'units',
          },
          {
            name: 'groups',
            icon: 'GrCatalog',
            url: 'catalog/groups',
            id: 'catalog-groups',
          },
        ],
      },
    ],
  },
  {
    name: 'customer.management',
    id: 'customer.management',
    submenu: [
      {
        name: 'wallets',
        icon: 'wallet',
        url: 'wallets',
        id: 'wallets',
        children: [],
      },
      {
        name: 'users',
        id: 'user',
        icon: 'user',
        url: 'users',
        children: [
          {
            icon: 'user',
            url: 'users/user',
            name: 'clients',
            id: 18,
          },
          {
            icon: 'userGroupAdd',
            url: 'users/admin',
            name: 'users',
            id: 19,
          },
          {
            icon: 'userSwitch',
            url: 'users/role',
            name: 'roles',
            id: 20,
          },
        ],
      },
      {
        icon: 'referral',
        url: 'settings/referal',
        name: 'referral',
        id: 'referral',
        children: [],
      },
      {
        name: 'email.subscriber',
        icon: 'mail',
        url: 'email/subscriber',
        id: 'email.subscriber',
        children: [
          {
            icon: 'MdNotificationAdd',
            url: 'subscriber',
            name: 'subscriber',
            id: 'subscriber',
          },
          {
            icon: 'MdNotificationAdd',
            url: 'message/subscriber',
            name: 'message.subscriber',
            id: 'message.subscriber',
          },
        ],
      },
    ],
  },
  // {
  //   name: 'deliveryman.management',
  //   id: 'deliveryman.management',
  //   submenu: [
  //     // {
  //     //   name: 'deliveries.list',
  //     //   icon: 'TbTruckDelivery',
  //     //   id: 'deliveries_list',
  //     //   url: 'deliveries/list',
  //     //   children: [],
  //     // },
  //     // {
  //     //   name: 'deliveries.map',
  //     //   icon: 'TbSitemap',
  //     //   id: 'deliveries_map',
  //     //   url: 'deliveries/map',
  //     //   children: [],
  //     // },
  //     {
  //       name: 'delivery.orders',
  //       icon: 'fiShoppingCart',
  //       id: 'delivery_orders',
  //       url: 'delivery/orders',
  //       children: [],
  //     },
  //     {
  //       name: 'delivery.statistics',
  //       icon: 'ImStatsDots',
  //       id: 'delivery.statistics',
  //       url: 'delivery/statistics',
  //       children: [],
  //     },
  //     // {
  //     //   name: 'deliveryboy.reviews',
  //     //   icon: 'TbTruckDelivery',
  //     //   url: 'reviews/deliveryboy',
  //     //   id: 'deliveryboy-review',
  //     //   children: [],
  //     // },
  //   ],
  // },
  {
    name: 'content.management',
    id: 'content.management',
    submenu: [
      {
        name: 'banners',
        icon: 'bsImage',
        url: 'banners',
        id: 10,
        children: [],
      },
      {
        name: 'blogs',
        url: 'blogs',
        icon: 'form',
        id: 'blogs',
        children: [],
      },
      {
        name: 'gallery',
        url: 'gallery',
        icon: 'fiImage',
        id: 17,
        children: [],
      },
      {
        name: 'notifications',
        icon: 'notificationsActive',
        url: 'notifications',
        id: 11,
        children: [],
      },
    ],
  },
  {
    name: 'transaction.management',
    id: 'transaction.management',
    submenu: [
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'transactions',
        id: 'transactions',
        children: [],
      },
      {
        name: 'payout.requests',
        icon: 'dollar',
        url: 'payout-requests',
        id: 'payout-requests',
        children: [],
      },
      {
        name: 'payouts',
        icon: 'dollar',
        url: 'payouts',
        id: 'payouts',
        children: [],
      },
      {
        name: 'subscriptions',
        icon: 'imSubscript',
        url: 'subscriptions',
        id: 13,
        children: [],
      },
      {
        name: 'cashback',
        icon: 'copyright',
        url: 'cashback',
        id: 'cashback',
        children: [],
      },
    ],
  },
  // {
  //   name: 'tickets',
  //   icon: 'project',
  //   url: 'tickets',
  //   id: 24,
  // },
  {
    name: 'business.settings',
    id: 'business.settings',
    submenu: [
      {
        icon: 'settings',
        url: 'settings/general',
        name: 'settings.general',
        id: 'settings.general',
        children: [],
      },
      {
        icon: 'moneyCollect',
        url: 'currencies',
        name: 'currencies',
        id: 'currencies',
        children: [],
      },
      {
        icon: 'wallet',
        url: 'settings/payments',
        name: 'payments',
        id: 'payments',
        children: [],
      },
      {
        icon: 'message',
        url: 'settings/sms-gateways',
        name: 'sms-gateways',
        id: 'sms-gateways',
        children: [],
      },
      {
        icon: 'emailSettings',
        url: 'settings/emailProviders',
        name: 'email.provider',
        id: 'email.provider',
        children: [],
      },
      {
        icon: 'notificationsActive',
        url: 'settings/firebase',
        name: 'notification.settings',
        id: 'notification.settings',
        children: [],
      },
      {
        icon: 'instagram',
        url: 'settings/social',
        name: 'social.settings',
        id: 'social-settings',
        children: [],
      },
      {
        icon: 'settings',
        url: 'settings',
        name: 'page.setup',
        id: 'page.setup',
        children: [
          {
            icon: 'questionCircle',
            url: 'settings/faqs',
            name: 'FAQ',
            id: 'faq',
          },
          {
            icon: 'paperClip',
            url: 'settings/terms',
            name: 'terms',
            id: 'terms',
          },
          {
            icon: 'lock',
            url: 'settings/policy',
            name: 'policy',
            id: 'policy',
          },
        ],
      },
    ],
  },
  {
    name: 'system.settings',
    id: 'system.settings',
    submenu: [
      {
        icon: 'global',
        url: 'settings/languages',
        name: 'languages',
        id: 'languages',
        children: [],
      },
      {
        icon: 'translation',
        url: 'settings/translations',
        name: 'translations',
        id: 'translations',
        children: [],
      },
      {
        icon: 'database',
        url: 'settings/backup',
        name: 'backup',
        id: 'backup',
        children: [],
      },
      {
        icon: 'tool',
        url: 'settings/system-information',
        name: 'system.information',
        id: 'system.information',
        children: [],
      },
      {
        icon: 'cloudUpload',
        url: 'settings/update',
        name: 'update',
        id: 'update',
        children: [],
      },
    ],
  },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

const sellerRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard',
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'seller/pos-system',
    id: 'pos-system',
  },
  {
    name: 'order.management',
    id: 'order.management',
    submenu: [
      {
        name: 'orders',
        icon: 'fiShoppingCart',
        url: 'seller/orders',
        id: 'orders',
        children: [],
      },
    ],
  },
  {
    name: 'shop.management',
    id: 'shop.management',
    submenu: [
      {
        name: 'my.shop',
        icon: 'shop',
        url: 'my-shop',
        id: 'my-shop',
      },

      {
        name: 'categories',
        icon: 'appStore',
        url: 'seller/categories',
        id: 'categories',
        children: [],
      },
      {
        name: 'branch',
        icon: 'branchesOutlined',
        url: 'seller/branch',
        id: 'branch',
        children: [],
      },
      {
        name: 'users',
        icon: 'user',
        url: 'seller/shop-users',
        id: 'users',
        children: [],
      },
      {
        name: 'recipes',
        icon: 'orderedList',
        url: 'seller/recipes',
        id: 'recipes',
      },
    ],
  },
  {
    name: 'product.management',
    id: 'product.management',
    submenu: [
      {
        name: 'discounts',
        icon: 'euroCircle',
        url: 'seller/discounts',
        id: 'discounts',
        children: [],
      },
      {
        icon: 'dropbox',
        url: 'seller/products',
        name: 'product',
        id: 'dropbox',
        children: [],
      },
    ],
  },
  {
    name: 'marketing',
    id: 'restaurant.management',
    submenu: [
      {
        name: 'coupons',
        icon: 'calendar',
        url: 'coupons',
        id: 'coupons',
        children: [],
      },
      {
        icon: 'GiftOutlined',
        name: 'shop.bonus',
        url: 'seller/bonus/shop',
        id: 'bonus/shop',
        children: [],
      },
      {
        icon: 'GiftOutlined',
        name: 'product.bonus',
        url: 'seller/bonus/product',
        id: 'bonus/product',
      },
    ],
  },
  {
    name: 'transaction.management',
    id: 'transaction.management',
    submenu: [
      {
        name: 'payments',
        icon: 'wallet',
        url: 'seller/payments',
        id: 'payments',
        children: [],
      },
      // {
      //   name: 'transactions',
      //   icon: 'transaction',
      //   url: 'seller/transactions',
      //   id: 'transactions',
      //   children: [],
      // },
      {
        name: 'payouts',
        icon: 'dollar',
        url: 'seller/payouts',
        id: 'payouts',
        children: [],
      },
    ],
  },
  {
    name: 'business.management',
    id: 'business.management',
    submenu: [
      {
        name: 'subscriptions',
        icon: 'trophy',
        url: 'seller/subscriptions',
        id: 'subscription',
        children: [],
      },
    ],
  },
  {
    name: 'delivery.management',
    id: 'delivery.management',
    submenu: [
      {
        icon: 'deliveryDining',
        name: 'delivery',
        url: 'seller/delivery/list',
        id: 15,
      },
      {
        icon: 'deliveryDining',
        name: 'deliveryman',
        url: 'seller/delivery/deliveryman',
        id: 16,
      },
    ],
  },
  {
    name: 'content.management',
    id: 'content.management',
    submenu: [
      {
        name: 'brands',
        icon: 'appStoreAdd',
        url: 'seller/brands',
        id: 'brands',
        children: [],
      },
      {
        name: 'banners',
        icon: 'bsImage',
        url: 'seller/banner',
        id: 'SellerBanner',
      },
    ],
  },
  {
    name: 'invites',
    icon: 'orderedList',
    url: 'seller/invites',
  },
  // {
  //   name: 'deliveryman',
  //   icon: 'deliveryDining',
  //   url: 'seller/delivery/deliveryman',
  //   id: 'deliveryman',
  // },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

const moderatorRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard',
  },
  {
    name: 'pos.system',
    icon: 'laptop',
    url: 'seller/pos-system',
    id: 'pos-system',
  },
  {
    icon: 'dropbox',
    url: 'seller/products',
    name: 'Products',
    id: 'dropbox',
  },
  {
    name: 'categories',
    icon: 'appStore',
    url: 'seller/categories',
    id: 'categories',
  },
  {
    name: 'brands',
    icon: 'appStoreAdd',
    url: 'seller/brands',
    id: 'brands',
  },
  {
    name: 'my.shop',
    icon: 'shop',
    url: 'my-shop',
    id: 'my-shop',
  },
  {
    name: 'orders',
    icon: 'fiShoppingCart',
    url: 'seller/orders',
    id: 'orders',
  },
  {
    name: 'discounts',
    icon: 'euroCircle',
    url: 'seller/discounts',
    id: 'discounts',
  },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

const deliverymanRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard',
  },
  {
    name: 'orders',
    icon: 'fiShoppingCart',
    url: 'deliveryman/orders',
    id: 'orders',
  },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

export const data = {
  admin: adminRoutes,
  manager: managerRoutes,
  seller: sellerRoutes,
  moderator: moderatorRoutes,
  deliveryman: deliverymanRoutes,
};
